### ISSUE TITLE
Problem in connecting 

### ISSUE THREAD

**Issue by zartakk** [DiegoGarciaMartin/Socket.IO-Cordova-Chat#1]
hi 
I ran the project on my android device as you told but after entering the username , the button connect doesn't work properly, and I couldn't connect  and see the next page of app.  The "Socket.IO Responsive chat" is also run as the background.
So, what is the problem ??

**Comment by DiegoGarciaMartin** [comment]
Hello,

If you edited the file 'src/www/js/chat.min.js' with the IP of the chat's back end, it should works.

If you access to the "Socket.IO Responsive chat" in the browser, it works?

**Comment by zartakk** [comment]
Thanks for your attention, yes you were right. It was some problems with editing it, that solved.
